 name: Build Docs
 on:
   push:
     branches:
     - master
     - main
 jobs:
   docs:
     name: CI (${{ matrix.os }}-${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: ['ubuntu-latest']
         environment-file: [.ci/38.yml]

     steps:
       - name: checkout repo
         uses: actions/checkout@v2

       - name: setup micromamba
         uses: mamba-org/provision-with-micromamba@main
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
           mamba-version: "*"
           channels: conda-forge
           channel-priority: true

       - name: install geosnap - bash
         shell: bash -l {0}
         run: pip install -e . --no-deps --force-reinstall
         if: matrix.os != 'windows-latest'

       - name: build docs
         shell: bash -l {0}
         run: cd docs; make html

       - name: Commit documentation changes
         run: |
           git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
           cp -r docs/_build/html/* gh-pages/
           cd gh-pages
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
           git commit -m "Update documentation" -a || true
           # The above command will fail if no changes were present, so we ignore
           # the return code.
  
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
            branch: gh-pages
            directory: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
