name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * 1,4"

jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        environment-file:
          - .ci/39.yml
          - .ci/310.yml
          - .ci/311.yml
        include:
          - environment-file: .ci/310.yml
            os: macos-latest
          - environment-file: .ci/310.yml
            os: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"

      - name: Install geosnap
        run: pip install . ;python geosnap/tests/_dl_data.py;
        env:
          COMBO_DATA: ${{ secrets.COMBO_DATA }}
  
      - name: Test geosnap
        run: |
          pytest -v --color yes --cov geosnap --cov-append --cov-report term-missing --cov-report xml .

      - uses: codecov/codecov-action@v3

      - name: Generate and publish the report
        if: |
          failure()
          && steps.status.outcome == 'failure'
          && github.event_name == 'schedule'
          && github.repository_owner == 'pysal'
        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: pytest-log.jsonl